services:
  - type: web
    name: react-django-project
    env: python
    plan: free
    region: oregon   # change if needed
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn backend.wsgi
    autoDeploy: true
